### ISSUE TITLE
Automation TODO

### ISSUE THREAD

**Issue by go-zen-chu** [go-zen-chu/hachi#1]
## GitHub & JIRA
- [ ] Analyse JIRA and post it to github
  - showing stats like number of tickets solved in one day, who was most assigned,...
- [ ] Parse Github PR or git branch and link to JIRA ticket
  - Parse Github issue and link to JIRA ticket

## GitHub & Slack
- [ ] Parse PR summary like dates and post it to Slack
- [ ] Post unclosed PR to Slack daily

## GitHub
- [ ] Add github label automatically for given PR
  - Parse DNM

### JIRA & Slack
- There are integration that notice jira ticket update to slack
